name: md2zhihu

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-for-zhihu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
      - name: Build for Zhihu
        uses: wangzhaode/md2zhihu@main
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pattern: |
            _posts/*.md
          asset_repo: https://wangzhaode:${{ secrets.GITEE_PAT }}@gitee.com/wangzhaode/asset.git@main-md2zhihu-asset
          target_platform: 'zhihu'
          output_branch: '${{ github.ref_name }}-md2zhihu'